site_name: Test Software Documentation
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/images/unops-favicon.png
  favicon: assets/images/unops-favicon.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

nav:
  - Home: index.md
  - HID:
      - Architecture Blueprint: HID/Architecture-Blueprint.md
      - Optimization: HID/Optimization.md
      - Resilience Planning: HID/Resilience-planning.md
      - System Blueprint: HID/System-Blueprint.md
  - Architecture:
      - Topology: Architecture/Network-Topology.md
      - Segmentation: Architecture/Network-Segmentation.md
      - Security Policy: Architecture/Security-Policy.md
  - Requirements:
      - Business and Technical: Requirement/Business-and-Technical.md
      - Critical Safeguards: Requirement/Critical-Safeguards.md
      - Usage Insights: Requirement/Usage-Insight.md
extra:
  favicon: assets/images/unops-favicon.png

markdown_extensions:
  - tables
